name: NGSCheckMate
channels:
    - anaconda
    - conda-forge
    - bioconda
dependencies:
    - python=3.8
    - samtools=1.3.1
    - bcftools=1.9
    - make
    - zlib
    - gxx_linux-64
    - pip
    - pip:
        - requests
        - git+https://github.com/SimBioSysInc/MAFpy.git